# Generated by Django 2.1.3 on 2018-12-03 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=200, size=None)),
                ('compare_img', models.ImageField(upload_to='')),
                ('returns_img', models.ImageField(upload_to='')),
                ('markowitz_img', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
