# Generated by Django 2.1.3 on 2018-12-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='compare_img',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='markowitz_img',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='returns_img',
        ),
    ]
